### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by jakobkogler** [allexks/py-polynomial#42]
The version on Pypi is currently broken.

```
>>> from polynomial import Polynomial as P
>>> P(1, 0) * P(1, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/polynomial/__init__.py", line 247, in __mul__
    result += s_m * o_m
  File ".../site-packages/polynomial/__init__.py", line 286, in __mul__
    return Monomial(self.a * other.a, self.degree + other.degree)
  File ".../site-packages/polynomial/__init__.py", line 107, in __getattr__
    return self[self.degree - ord(name.lower()) + ord('a')]
  File ".../site-packages/polynomial/__init__.py", line 129, in __getitem__
    degree {0} of a {1}-degree polynomial".format(degree, self.degree))
IndexError: Attempt to get coefficient of term with degree -inf of a -inf-degree polynomial
```

I just spend an hour debugging the problem until I realized that the master branch doesn't have the problem anymore. Probably would be a good idea to release a new version...

**Comment by allexks** [comment]
I am very sorry for the trouble you had. Version [0.5.0](https://pypi.org/project/py-polynomial/0.5.0/) is published now.
